[package]
name = "stm32-usbd"
version = "0.5.1"
edition = "2018"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>", "Vadim Kaushan <admin@disasm.info>", "Nicolas Stalder <n@stalder.io>", "Jonas Martin <lichtfeind@gmail.com>"]
description = "'usb-device' implementation for STM32 microcontrollers"
license = "MIT"
repository = "https://github.com/stm32-rs/stm32-usbd"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]

[dependencies]
vcell = "0.1.2"
cortex-m = "0.6.1"
#usb-device = "0.2.3"
#usb-device = {path = "../usb-device"}
usb-device = {git = "https://github.com/sjames/usb-device.git"}

#[dependencies.defmt]
#git = "https://github.com/knurling-rs/defmt"
#branch = "main"

[dev-dependencies]
stm32f1xx-hal = { version = "0.4.0", features = ["stm32f103"] }

[features]
# USB RAM access scheme
ram_access_1x16 = []
ram_access_2x16 = []
#default = [
#  "defmt-default",
#  # "dependency-a/defmt-trace",
#]

#defmt-default = []
#defmt-trace = []
#defmt-debug = []
#defmt-info = []
#defmt-warn = []
#defmt-error = []
